### ISSUE TITLE
メール機能のテストについて

### ISSUE THREAD

**Issue by haruyan-hopemucci** [haruyan-hopemucci/wp-bistro-calme#6]
とりあえずメールの送受信だけ確認したい場合は、外部連携する必要はなくdockerでメールサーバーを立てれば良い。

docker-compose.yml
```yml
version: '3'

services:
  # MailServer
  maildev:
    image: maildev/maildev
    ports:
    - 1080:1080
    - 25:1025
```
これを実行すると、localの25ポートでメール待受し、http://localhost:1080/にて送信されたメールの内容がチェックできる。

次にmampのphp設定そのままだとsendmailコマンドを使われるので、[MW WP Form](https://plugins.2inc.org/mw-wp-form/)プラグインを導入してlocalhostのメールサーバーにメールを転送する設定を行う。

### 設定内容の抜粋

- ホスト名: Other smpt => localhost
- ポート: 25
- 暗号化をオフ
- Authentication をオフ
